[package]
name = "tanks"
version = "0.1.0"
authors = ["Jonathan Louie <jonathanrlouie@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.0"

[profile.release]
lto = true
